server:
  port: 7000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/control
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL57Dialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always